LIBNAME AMA_L "/folders/myshortcuts/WRDS2/bvd/ama_l";

PROC SQL;
	CREATE TABLE COLUMNS AS
		SELECT *  
		FROM DICTIONARY.COLUMNS
	WHERE
	TYPE EQ "char" AND
	MEMNAME EQ "AMADEUS_L";
QUIT;
RUN;

PROC SQL;
	SELECT NAME INTO :COLS 
	SEPARATED BY ","
	FROM DICTIONARY.COLUMNS
	WHERE
	TYPE EQ "char" AND
	MEMNAME EQ "FINANCIALS_L";
	
	CREATE TABLE CHARS AS
	SELECT DISTINCT &COLS
	FROM AMA_L.FINANCIALS_L;
QUIT;
RUN;

%PUT &COLS;