OPTIONS SASAUTOS=('/wrds/wrdsmacros/', SASAUTOS) MAUTOSOURCE SOURCE NOCENTER LS=80 PS=MAX;
%INCLUDE "~/UTILITIES/UTILITIES.GENERAL.sas";

LIBNAME HOME "/scratch/uvanl";

LIBNAME CRSP "/wrds/crsp/sasdata/a_stock";
LIBNAME COMPG "/wrds/comp/sasdata/global";


PROC CONTENTS
    DATA=COMPG.G_SECD
    VARNUM
    DETAILS;
RUN;

DATA G_SECD;
    SET COMPG.G_SECD;
    YEAR = YEAR(DATADATE);
    MONTH = MONTH(DATADATE);
RUN;

PROC SORT DATA=G_SECD;
    BY GVKEY IID DATADATE;
RUN;

PROC SQL;
    CREATE TABLE GSECDSLO AS
        SELECT *
        FROM COMPG.G_SECD
        WHERE FIC = "SVN";
RUN;
QUIT;

PROC EXPAND
    DATA = GSECDSLO
    OUT = GSECDSLO_Q
    FROM = DAY
    TO = QTR;

    BY GVKEY IID;
    ID DATADATE;
    
    CONVERT _NUMERIC_ = _NUMERIC_ / OBSERVED = END;
RUN;


PROC PRINT DATA=GSECDSLO_Q; RUN;
PROC CONTENTS DATA=GSECDSLO_Q VARNUM; RUN;



PROC EXPAND
    DATA = COMPG.G_SECD
    OUT = HOME.GSECDSLO_M
    FROM = DAY
    TO = MONTH;

    BY GVKEY IID;
    ID DATADATE;
    
    CONVERT _NUMERIC_ = _NUMERIC_ / OBSERVED = END;
RUN;    


