OPTIONS SASAUTOS=('/wrds/wrdsmacros/', SASAUTOS) MAUTOSOURCE;
%INCLUDE "~/UTILITIES/UTILITIES.GENERAL.sas";



LIBNAME HOME "/scratch/uvanl";

LIBNAME AMA_L "/wrds/bvd/sasdata/ama_l";
LIBNAME AMA_M "/wrds/bvd/sasdata/ama_m";
LIBNAME AMA_S "/wrds/bvd/sasdata/ama_s";
LIBNAME AMA_V "/wrds/bvd/sasdata/ama_v";

OPTIONS SOURCE NOCENTER LS=80 PS=MAX;


PROC DATASETS
    LIBRARY = AMA_L
    MEMTYPE = DATA
    DETAILS;
RUN;

PROC CONTENTS
    DATA=AMA_S.COMPANY_S
    VARNUM
    DETAILS;
RUN;


/*=============================================================================\
| CHECK THE NUMBER OF DISTINCT FIRMS IN THE AMADEUS                            |
\=============================================================================*/
PROC SQL;
    CREATE TABLE AMADEUS_ALLIDS AS
        SELECT DISTINCT IDNR, CNTRYCDE, NUMYEARS, LSTATUS FROM AMA_L.COMPANY_L
        OUTER UNION CORR
        SELECT DISTINCT IDNR, CNTRYCDE, NUMYEARS, LSTATUS FROM AMA_V.COMPANY_V
        OUTER UNION CORR
        SELECT DISTINCT IDNR, CNTRYCDE, NUMYEARS, LSTATUS FROM AMA_S.COMPANY_S
        OUTER UNION CORR
        SELECT DISTINCT IDNR, CNTRYCDE, NUMYEARS, LSTATUS FROM AMA_M.COMPANY_M;
QUIT;

PROC SQL;
    CREATE TABLE AMADEUS_INACTIVE AS
        SELECT *
        FROM AMA_L.COMPANY_L AS A
        WHERE A.LSTATUS <> "Active"
        OUTER UNION CORR
        SELECT *
        FROM AMA_S.COMPANY_S AS B
        WHERE B.LSTATUS <> "Active"
        OUTER UNION CORR
        SELECT *
        FROM AMA_M.COMPANY_M AS C
        WHERE C.LSTATUS <> "Active"
        OUTER UNION CORR
        SELECT *
        FROM AMA_V.COMPANY_V AS D
        WHERE D.LSTATUS <> "Active";
QUIT;

PROC EXPORT
    DBMS=CSV
    DATA=AMADEUS_UNACTIVE
    OUTFILE="/scratch/uvanl/amadeus.bankrupt.list.csv"
    REPLACE;
RUN;


PROC FREQ DATA=AMADEUS_ALLIDS;
    TABLES CNTRYCDE NUMYEARS LSTATUS;
RUN;

PROC PRINT DATA=AMADEUS_ALLIDS (OBS=10);
RUN;

PROC PRINT DATA=AMADEUS_UNACTIVE (OBS=10);
RUN;

PROC CONTENTS DATA=AMADEUS_UNACTIVE VARNUM;
RUN;

PROC FREQ DATA=AMADEUS_UNACTIVE;
    TABLES COUNTRY*LSTATUS;
RUN;




